routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::resource('students','StudentsController');
    Route::resource('staff','StaffController');
    Route::resource('institute','InstituteController');
    Route::get('search/{table}','SearchController@search');
    $directory= __DIR__.'/Generator';
    $files=scandir($directory);
    foreach($files as $file){
        $array=explode('.',$file);
        if(end($array)=='php'){
           require $directory.'/'.$file;
        }
    }
	Route::group(['prefix'=>'settings','as'=>'settings.','namespace'=>'settings'],function(){
	   Route::resource('department','DepartmentController');
    });
});

app/Models/Institute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Institute extends Model
{
    protected $table="institutes";
    //
    protected $fillable =[
		'name',
		'abbr',
		'full_abbr',
    ];
}

app/Http/Controllers/InstituteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Institute;
use App\Http\Requests\InstituteRequest;
use Illuminate\Support\Facades\Hash;

class InstituteController extends Controller
{
    /**
     * Display a listing of the institute
     *
     * @param  \App\Institute  $model
     * @return \Illuminate\View\View
     */
    public function index(Institute $model)
    {
        return view('institute.index', ['institute' => $model->paginate(20)]);
    }
    /**
     * Show the form for creating a new institute
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('institute.create');
    }

    /**
     * Store a newly created institute in storage
     *
     * @param  \App\Http\Requests\InstituteRequest  $request
     * @param  \App\Institute  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(InstituteRequest $request, Institute $model)
    {
        $model->create($request->all());

        return redirect()->route('institute.index')->withStatus(__('Institute successfully created.'));
    }

    /**
     * Show the form for editing the specified institute
     *
     * @param  \App\Institute  $institute
     * @return \Illuminate\View\View
     */
    public function edit(Institute $institute)
    {
        return view('institute.edit', compact('institute'));
    }

    /**
     * Update the specified institute in storage
     *
     * @param  \App\Http\Requests\InstituteRequest  $request
     * @param  \App\Institute  $institute
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(InstituteRequest $request, Institute  $institute)
    {
        $institute->update($request->all());
        return redirect()->route('institute.index')->withStatus(__('Institute successfully updated.'));
    }

    /**
     * Remove the specified institute from storage
     *
     * @param  \App\Institute  $institute
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Institute  $institute)
    {
        $institute->delete();

        return redirect()->route('institute.index')->withStatus(__('Institute successfully deleted.'));
    }
}

resources/views/institute/create.blade.php
@extends('layouts.app', ['activePage' => 'institute-management', 'titlePage' => __('Institute Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('institute.store') }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Add Institute') }}</h4>
                <p class="card-category"></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('institute.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                  </div>
                </div>
							<div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Name') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Name') }}" value="{{ old('name') }}" required="true" aria-required="true"/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
							<div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Abbr') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('abbr') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('abbr') ? ' is-invalid' : '' }}" name="abbr" id="input-abbr" type="text" placeholder="{{ __('Abbr') }}" value="{{ old('abbr') }}" required="true" aria-required="true"/>
                      @if ($errors->has('abbr'))
                        <span id="abbr-error" class="error text-danger" for="input-abbr">{{ $errors->first('abbr') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
							<div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Full_abbr') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('full_abbr') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('full_abbr') ? ' is-invalid' : '' }}" name="full_abbr" id="input-full_abbr" type="text" placeholder="{{ __('Full_abbr') }}" value="{{ old('full_abbr') }}" required="true" aria-required="true"/>
                      @if ($errors->has('full_abbr'))
                        <span id="full_abbr-error" class="error text-danger" for="input-full_abbr">{{ $errors->first('full_abbr') }}</span>
                      @endif
                    </div>
                  </div>
                </div>                
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Add Institute') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/institute/edit.blade.php
@extends('layouts.app', ['activePage' => 'institute-management', 'titlePage' => __('Institute Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('institute.update', $institute) }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('put')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Edit Institute') }}</h4>
                <p class="card-category"></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('institute.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                  </div>
                </div>
							<div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Name') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Name') }}" value="{{ old('name', $institute->name) }}" required="true" aria-required="true"/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
							<div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Abbr') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('abbr') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('abbr') ? ' is-invalid' : '' }}" name="abbr" id="input-abbr" type="text" placeholder="{{ __('Abbr') }}" value="{{ old('abbr', $institute->abbr) }}" required="true" aria-required="true"/>
                      @if ($errors->has('abbr'))
                        <span id="abbr-error" class="error text-danger" for="input-abbr">{{ $errors->first('abbr') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
							<div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Full_abbr') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('full_abbr') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('full_abbr') ? ' is-invalid' : '' }}" name="full_abbr" id="input-full_abbr" type="text" placeholder="{{ __('Full_abbr') }}" value="{{ old('full_abbr', $institute->full_abbr) }}" required="true" aria-required="true"/>
                      @if ($errors->has('full_abbr'))
                        <span id="full_abbr-error" class="error text-danger" for="input-full_abbr">{{ $errors->first('full_abbr') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/institute/index.blade.php
@extends('layouts.app', ['activePage' => 'institute-management', 'titlePage' => __('Institute Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">{{ __('Institute') }}</h4>
                <p class="card-category"> {{ __('Here you can manage institute') }}</p>
              </div>
              <div class="card-body">
                @if (session('status'))
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <i class="material-icons">close</i>
                        </button>
                        <span>{{ session('status') }}</span>
                      </div>
                    </div>
                  </div>
                @endif
                <div class="row">
                    <div class=" col-7 right no-border">
                        <input id="searchTable" type="text" value="" class="form-control" placeholder="Search...">
                    </div>
                    <div class="col-5 text-right">
                        <a href="{{ route('institute.create') }}" class="btn btn-sm btn-primary">{{ __('Add Institute') }}</a>
                    </div>
                </div>
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-primary">
                    <th>
                        {{ __('Id') }}
                    </th>
						<th>
                            {{ __("Name") }}
                          </th>
						<th>
                            {{ __("Abbr") }}
                          </th>
						<th>
                            {{ __("Full_abbr") }}
                          </th>
                      <th>
                        {{ __('Creation date') }}
                      </th>
                      <th class="text-right">
                        {{ __('Actions') }}
                      </th>
                    </thead>
                    <tbody>
                      @foreach($institute as $model)
                        <tr>
                            <td>
                                {{$model->id}}
                            </td>
						<td>
                            {{ $model->name }}
                          </td>
						<td>
                            {{ $model->abbr }}
                          </td>
						<td>
                            {{ $model->full_abbr }}
                          </td>
                          <td>
                            {{ $model->created_at->format('Y/m/d') }}
                          </td>
                          <td class="td-actions text-right">
                              <form action="{{ route('institute.destroy', $model) }}" method="post">
                                  @csrf
                                  @method('delete')
                              
                                  <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('institute.edit', $model) }}" data-original-title="" title="">
                                    <i class="material-icons">edit</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                  <button type="button" class="btn btn-danger btn-link" data-original-title="" title="" onclick="confirm('{{ __("Are you sure you want to delete this institute?") }}') ? this.parentElement.submit() : ''">
                                      <i class="material-icons">close</i>
                                      <div class="ripple-container"></div>
                                  </button>
                              </form>
                          </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                    {{ $institute->links() }}
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
@endsection
@section('after-script')
    <script type="text/javascript">
        $(document).ready(function () {
            $('#searchTable').on('keyup',function(e){
                d=$('.search-content');
                for(let i=0;i<d.length;i++){
                    if(d[i].innerText.match(e.target.value)){
                        d[i].parentElement.removeAttribute('style');
                        continue;
                    }
                    d[i].parentElement.style.display='none';
                }
            })
        })
    </script>
@endsection